### ISSUE TITLE
Release Community meeting recording (July)

### ISSUE THREAD

**Issue by kravciak** [kubewarden/community#10]
## Acceptance criteria

- [x] Upload the recording on our youtube channel
- To double check:
  - [x] Recording is ordered (should be last one)
  - [x] Recording has description

## Description:

This meeting’s agenda:

```
1.14 release
  - Workaround for PolicyServer certificates
  - Domain qualified finalizers
  - New host capability & cel-policy update
  - kwctl scaffold vap

Policies changes and fixes
  - User-group-policy now is able to check container image user
  - Env-var-policy know can validate names only

What’s coming next
```

## Recording link

https://zoom.us/rec/play/-EAI3oA8glc16SguF7XRUvv4SPdyVhzW13aNkM8AA2p-tb-merCo-GMU1klxlj15bfuWh67_SPMZ9buf.BvEF_gunJDnvQq36?canPlayFromShare=true&from=my_recording&startTime=1720713709000&componentName=rec-play&originRequestUrl=https%3A%2F%2Fzoom.us%2Frec%2Fshare%2FefsnUg8t0ui7BUiGpJjPYEFzFilq1Ws3WhqvYmeakx4IBdu6A8oZVPTpQ25T4O-U.BnUywpxArhryFQai%3FstartTime%3D1720713709000

**Comment by robertsirc** [comment]
This is done.
