### ISSUE TITLE
Release Community meeting recording (October)

### ISSUE THREAD

**Issue by kravciak** [kubewarden/community#20]
## To double check
  -  Recording is ordered (should be last one)
  -  Recording has description

## Meeting’s agenda:

```
This meeting’s agenda:
- 1.17 released
  - Cert-manager removal
  - Policy groups

- What’s coming next:
  - SLSA level 3
  - Short names in crds
  - v1alpha crds removal?

- General:
  - Ndots policy
  - Trusted-repos-policy rewrite
  - Helm charts testing automation
  - Kubecon NA Kubewarden booth
```

## Recording link

First part: https://zoom.us/rec/share/QaWPZnQWpil3rg6sTz3a9vKsopCY-YyRW6fZ7LbHyHkfkbc7OzpgTuhjQLh20FLP.wu_fYtaNaqd9aeUg?startTime=1728576111000
Second part: https://zoom.us/rec/share/QaWPZnQWpil3rg6sTz3a9vKsopCY-YyRW6fZ7LbHyHkfkbc7OzpgTuhjQLh20FLP.wu_fYtaNaqd9aeUg?startTime=1728577162000

Sadly, I (viccuad) misclicked and stopped the recording half through, They need to be spliced together.

**Comment by viccuad** [comment]
Ready for upload.

**Comment by robertsirc** [comment]
we need to splice these together?

**Comment by kravciak** [comment]
> @kravciak do we need to splice these together?

hi Robert, I spliced it (no editing) - https://www.filemail.com/d/xagwprhefntefpg

**Comment by viccuad** [comment]
@robertsirc ping, just in case it got forgotten.

**Comment by robertsirc** [comment]
On this now.

**Comment by robertsirc** [comment]
Done
