### ISSUE TITLE
Submit application form to have KW promoted to incubation

### ISSUE THREAD

**Issue by flavio** [kubewarden/community#24]
This is part of [this EPIC](https://github.com/kubewarden/community/issues/11).

### Acceptance criteria:

- [x] submit application form

**Comment by jvanz** [comment]
I've submitted Kubewarden for the [incubation level](https://github.com/cncf/toc/issues/1497). Please review the issue and let me know if you noticed something wrong or missing data.

**Comment by flavio** [comment]
Thanks a lot :heart: 

> Achieve the Open Source Security Foundation (OpenSSF) Best Practices passing badge.

Isn't this check already passing?

**Comment by jvanz** [comment]
> > Achieve the Open Source Security Foundation (OpenSSF) Best Practices passing badge.
> 
> Isn't this check already passing?

We need to fix one issue in [policy server](https://github.com/kubewarden/policy-server) and [kwctl](https://github.com/kubewarden/kwctl). There is one item missing. @viccuad already created issue to address that. Both issues are listed in the acceptance criteria of the [epic](https://github.com/kubewarden/community/issues/11)

**Comment by flavio** [comment]
The submission is done, closing
