### ISSUE TITLE
Release Community meeting recording (November)

### ISSUE THREAD

**Issue by kravciak** [kubewarden/community#28]
## To double check
  -  Recording is ordered (should be last one)
  -  Recording has description

## Meeting’s agenda:

```
This meeting’s agenda:
- 1.18 released
  - SLSA level 3
  - Deprecation of v1alpha2
  - CRD short names
- What’s coming next
- General:
  - Kubecon NA Kubewarden booth
```

## Recording link

https://zoom.us/rec/share/Odgos8iuKzSHNMmkFPvPInqILFu6dUWqoPaR4l4LcLl-ljINmkLsjqKFeJjkIvJ-.hBiW9KrEHwFokJ05

**Comment by robertsirc** [comment]
On it now.

**Comment by robertsirc** [comment]
This is done.
