### ISSUE TITLE
Publish meeting recording for December

### ISSUE THREAD

**Issue by flavio** [kubewarden/community#30]
### Meeting Agenda

```markdown
- 1.19 released:
  - Fix to Policy-Server CI and SBOM file generation
  - Removal of Old Post-Install Helm Chart Hooks
  - Updated OpenTelemetry CRDs to Beta v1
- What’s coming next
  - Opentelemetry changes
  - Porting Rego policies
```

### Recording Link

https://zoom.us/rec/play/otMAIC9hiHx-pdh-8A_ZZNuSP0fJnUF_4_tWlHiecGyjB8JSplmod8q3kBMREopN2HLWb4y0LCetnNKD.1bVRFxnt9Ufy_50b?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fzoom.us%2Frec%2Fshare%2FGOHGW3INKBJI4_pWI8BEpnl3_v_5-wvQG71b-dn57INm5_YLf7Kl4RxJWNFxMfFz.3JtcvKwjoeqtOI5m

**Comment by robertsirc** [comment]
I am on it now.

**Comment by robertsirc** [comment]
This is done.
