### ISSUE TITLE
Release Community meeting recording (April)

### ISSUE THREAD

**Issue by kravciak** [kubewarden/community#7]
## Acceptance criteria

- [x] Upload the recording on our youtube channel
- To double check:
  - [x] Recording is ordered (should be last one)
  - [x] Recording has description

## Description:

This meeting’s agenda:

```
New community repository - https://github.com/kubewarden/community
CNCF domain transfer in progress
Container Resources Policy update

Upcoming 1.12 release
  - RC1 is available
  - PodDisruptionBudget configuration
  - added Limits & Requests to PolicyServer
  - added Affinity configuration to kubewarden-defaults

Upcoming 1.13 release
  - Policy-server memory usage
  - Controller optimizations
```

## Recording link

https://zoom.us/rec/play/Wz9Ae9zK2LhS9yYR4w1qoNCZp-G1Uh31mZJ4Pz3CJx2wElRIW3w6lh72A_Bt_SdfklpfnQhX-EIyf7Hu.wzeJP6aEVXIY56qR

**Comment by robertsirc** [comment]
Done

**Comment by robertsirc** [comment]
This is all done.
